### PR TITLE
removed useless repo thats for artificially augment your commit number to look cool

### PR DESCRIPTION
**Pull request by Nissyaniss**
:)

### CODE REVIEW

**Comment by ntilleul** [comment]
image

**Comment by mperrot36** [comment]
programmerhumor-io-linux-memes-backend-memes-08893227ba65697

**Comment by mperrot36** [comment]
i-just-want-to-be-part-of-your-symphony-symphony

**Comment by Rayzeq** [comment]
alt text

**Comment by Asgarrrr** [comment]
❤️

**Comment by Asgarrrr** [comment]
Your teammate https://github.com/Vexcited [(here)](https://github.com/Vexcited/Vexcited/commits/main/) is doing exactly the same thing x)

But fair point! My goal wasn’t to artificially boost my numbers—just exploring ways to organize and keep track of my work. But I can see how it might come across that way. Thanks for the feedback

**Pull request closed without merging**
